dist: trusty
sudo: required
addons:
  chrome: stable
before_install:
  -
language: node_js
node_js:
  - '8'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install --no-bin-links
  - npm install -g @angular/cli
script:
  - npm run $TEST_SUITE
notifications:
  email: false
env:
  - TEST_SUITE=unit
  - TEST_SUITE=e2e-travis
  - TEST_SUITE=lint