version: '3.5'
services:
  hpc_cdm:
    image: hpc-cdm
    hostname: cdm
    volumes:
      - .env.json:/var/www/config/config.json
    networks:
      service:
        aliases:
          - cdm
          - cdm.hpc.vm
    ports:
      - '127.0.0.1:4200:80'

networks:
  service:
    name: cdm_docker_local
