#!/bin/bash

set -e

echo "Starting the build..."

TARGET=development
ENVIRONMENT=devServer

if [ "$SOURCE_BRANCH" == "stage" ]; then
    TARGET=production
    ENVIRONMENT=stage
elif [ "$SOURCE_BRANCH" == "dev" ]; then
    TARGET=development
    ENVIRONMENT=devServer
elif [ "$SOURCE_BRANCH" == "demo" ]; then
    TARGET=production
    ENVIRONMENT=demo
fi

docker build \
    --build-arg ENVIRONMENT=$ENVIRONMENT \
    --build-arg TARGET=$TARGET \
    -t $IMAGE_NAME .
