name: Workflow

on: [push]

jobs:
  workflow:
    name: Run Workflow
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
    - uses: actions/checkout@master
    - name: Login to Docker
      if: ${{ github.actor != 'dependabot[bot]' }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - uses: UN-OCHA/hpc-actions@develop
      env:
        CONFIG_FILE: .github/workflow.config.json
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}